### ISSUE TITLE
Practice Pagination

### ISSUE THREAD

**Issue by kelvin373-ht** [kelvin373-ht/ProjectAppAndroid#58]
Note for @ibnu009 

**Edit .gitignore**
Please, edit your gitignore become this
```
*.iml
.gradle
/local.properties
/.idea
.DS_Store
/build
/captures
.externalNativeBuild
.cxx
local.properties
```

**Clean Dependencies**
_- Upgrade version_
Example:
```com.google.android.material:material:1.2.1``` to ```com.google.android.material:material:1.4.0```

- Avoid duplicate implementation ( 1 duplicate: paging-rutntime )

- Delete androidTestImplementation and testImplementation because this projects is not used.

If you done fixing that, You comments this and I will merge :)
Thank you

**Comment by ibnu009** [comment]
I have edited my dependencies with the latest version also deleted unused and duplicate dependencies

**Comment by kelvin373-ht** [comment]
Good job.. @ibnu009 
But you should be focus your branch.
Next time, you push your branch not `master`. 
If you want to merge master or develop, tag me, please.

Thanks :)
